### ISSUE TITLE
new release? or deprecated?

### ISSUE THREAD

**Issue by rlam3** [perone/stallion#58]
new release? or deprecated?

**Comment by uhlhosting** [comment]
Take it like no one cares for now.

**Comment by perone** [comment]
Contributions are welcome 👍

**Comment by foozzi** [comment]
> 
> 
> new release? or deprecated?

welcome to new powerfull fork https://github.com/foozzi/cilantropy

**Comment by foozzi** [comment]
thank for support contributions 👍

**Comment by perone** [comment]
What I saw was not a contribution, but someone desperate trying to get attention to a fork that never submitted a pull-request.

**Comment by foozzi** [comment]
> What I saw was not a contribution, but someone desperate trying to get attention to a fork that never submitted a pull-request.

I didn't swear with you, I just wanted to fork the project and develop it, your names are all on the page in the "About" project, what do I need to do to make you happy?

**Comment by perone** [comment]
It is not about me, it is about open-source ethics. I don't fork a project and then I go there saying "look my new amazing fork !", I first submit a pull-request with the contributions, then if not accepted I would consider doing a fork for a new project, but even if I do a fork, I would never use the other project as a mean to advertise about it.

**Comment by foozzi** [comment]
> It is not about me, it is about open-source ethics. I don't fork a project and then I go there saying "look my new amazing fork !", I first submit a pull-request with the contributions, then if not accepted I would consider doing a fork for a new project, but even if I do a fork, I would never use the other project as a mean to advertise about it.

sorry, but I saw that there is no support for the code for a long time and decided to continue the project with the names of those who created it initially, maybe I should add your names to the README? No, seriously, I didn't want to offend anyone or advertise, why did I hurt you so much?
